networks:
  backuper: {}
services:
  backuper_mariadb_10_10:
    environment:
    - MARIADB_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mariadb:10.10.6
    networks:
    - backuper
    ports:
    - 12010:3306
    restart: 'no'
  backuper_mariadb_10_11:
    environment:
    - MARIADB_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mariadb:10.11.5
    networks:
    - backuper
    ports:
    - 12011:3306
    restart: 'no'
  backuper_mariadb_10_4:
    environment:
    - MARIADB_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mariadb:10.4.31
    networks:
    - backuper
    ports:
    - 11104:3306
    restart: 'no'
  backuper_mariadb_10_5:
    environment:
    - MARIADB_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mariadb:10.5.22
    networks:
    - backuper
    ports:
    - 11105:3306
    restart: 'no'
  backuper_mariadb_10_6:
    environment:
    - MARIADB_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mariadb:10.6.15
    networks:
    - backuper
    ports:
    - 11106:3306
    restart: 'no'
  backuper_mariadb_11_0:
    environment:
    - MARIADB_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mariadb:11.0.3
    networks:
    - backuper
    ports:
    - 11110:3306
    restart: 'no'
  backuper_mariadb_11_1:
    environment:
    - MARIADB_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mariadb:11.1.2
    networks:
    - backuper
    ports:
    - 11111:3306
    restart: 'no'
  backuper_mysql_5_7:
    environment:
    - MYSQL_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MYSQL_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MYSQL_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MYSQL_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mysql:5.7.43
    networks:
    - backuper
    ports:
    - 9057:3306
    restart: 'no'
  backuper_mysql_8_0:
    environment:
    - MYSQL_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MYSQL_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MYSQL_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MYSQL_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mysql:8.0.34
    networks:
    - backuper
    ports:
    - 9080:3306
    restart: 'no'
  backuper_mysql_8_1:
    environment:
    - MYSQL_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MYSQL_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MYSQL_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MYSQL_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mysql:8.1.0
    networks:
    - backuper
    ports:
    - 9081:3306
    restart: 'no'
  backuper_postgres_11:
    environment:
    - POSTGRES_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_DB=database-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_USER=user-_-12!@#%^&*()/;><.,]}{[
    image: postgres:11.21-bookworm
    networks:
    - backuper
    ports:
    - 10011:5432
    restart: 'no'
  backuper_postgres_12:
    environment:
    - POSTGRES_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_DB=database-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_USER=user-_-12!@#%^&*()/;><.,]}{[
    image: postgres:12.16-bookworm
    networks:
    - backuper
    ports:
    - 10012:5432
    restart: 'no'
  backuper_postgres_13:
    environment:
    - POSTGRES_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_DB=database-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_USER=user-_-12!@#%^&*()/;><.,]}{[
    image: postgres:13.12-bookworm
    networks:
    - backuper
    ports:
    - 10013:5432
    restart: 'no'
  backuper_postgres_14:
    environment:
    - POSTGRES_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_DB=database-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_USER=user-_-12!@#%^&*()/;><.,]}{[
    image: postgres:14.9-bookworm
    networks:
    - backuper
    ports:
    - 10014:5432
    restart: 'no'
  backuper_postgres_15:
    environment:
    - POSTGRES_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_DB=database-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_USER=user-_-12!@#%^&*()/;><.,]}{[
    image: postgres:15.4-bookworm
    networks:
    - backuper
    ports:
    - 10015:5432
    restart: 'no'
  backuper_postgres_16:
    environment:
    - POSTGRES_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_DB=database-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_USER=user-_-12!@#%^&*()/;><.,]}{[
    image: postgres:16.0-bookworm
    networks:
    - backuper
    ports:
    - 10016:5432
    restart: 'no'

