networks:
  backuper: {}
services:
  backuper_mariadb_10_11:
    environment:
    - MARIADB_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mariadb:10.11.6
    networks:
    - backuper
    ports:
    - 12011:3306
    restart: 'no'
  backuper_mariadb_10_4:
    environment:
    - MARIADB_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mariadb:10.4.32
    networks:
    - backuper
    ports:
    - 11104:3306
    restart: 'no'
  backuper_mariadb_10_5:
    environment:
    - MARIADB_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mariadb:10.5.23
    networks:
    - backuper
    ports:
    - 11105:3306
    restart: 'no'
  backuper_mariadb_10_6:
    environment:
    - MARIADB_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mariadb:10.6.16
    networks:
    - backuper
    ports:
    - 11106:3306
    restart: 'no'
  backuper_mariadb_11_0:
    environment:
    - MARIADB_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mariadb:11.0.4
    networks:
    - backuper
    ports:
    - 11110:3306
    restart: 'no'
  backuper_mariadb_11_1:
    environment:
    - MARIADB_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mariadb:11.1.3
    networks:
    - backuper
    ports:
    - 11111:3306
    restart: 'no'
  backuper_mariadb_11_2:
    environment:
    - MARIADB_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MARIADB_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mariadb:11.2.2
    networks:
    - backuper
    ports:
    - 11112:3306
    restart: 'no'
  backuper_mysql_8_0:
    environment:
    - MYSQL_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MYSQL_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MYSQL_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MYSQL_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mysql:8.0.35
    networks:
    - backuper
    ports:
    - 9080:3306
    restart: 'no'
  backuper_mysql_8_2:
    environment:
    - MYSQL_ROOT_PASSWORD=root-password-_-12!@#%^&*()/;><.,]}{[
    - MYSQL_DATABASE=database-_-12!@#%^&*()/;><.,]}{[
    - MYSQL_USER=user-_-12!@#%^&*()/;><.,]}{[
    - MYSQL_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    image: mysql:8.2.0
    networks:
    - backuper
    ports:
    - 9082:3306
    restart: 'no'
  backuper_postgres_12:
    environment:
    - POSTGRES_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_DB=database-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_USER=user-_-12!@#%^&*()/;><.,]}{[
    image: postgres:12.17-bookworm
    networks:
    - backuper
    ports:
    - 10012:5432
    restart: 'no'
  backuper_postgres_13:
    environment:
    - POSTGRES_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_DB=database-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_USER=user-_-12!@#%^&*()/;><.,]}{[
    image: postgres:13.13-bookworm
    networks:
    - backuper
    ports:
    - 10013:5432
    restart: 'no'
  backuper_postgres_14:
    environment:
    - POSTGRES_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_DB=database-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_USER=user-_-12!@#%^&*()/;><.,]}{[
    image: postgres:14.10-bookworm
    networks:
    - backuper
    ports:
    - 10014:5432
    restart: 'no'
  backuper_postgres_15:
    environment:
    - POSTGRES_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_DB=database-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_USER=user-_-12!@#%^&*()/;><.,]}{[
    image: postgres:15.5-bookworm
    networks:
    - backuper
    ports:
    - 10015:5432
    restart: 'no'
  backuper_postgres_16:
    environment:
    - POSTGRES_PASSWORD=password-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_DB=database-_-12!@#%^&*()/;><.,]}{[
    - POSTGRES_USER=user-_-12!@#%^&*()/;><.,]}{[
    image: postgres:16.1-bookworm
    networks:
    - backuper
    ports:
    - 10016:5432
    restart: 'no'

